
services:
  diarization:
    build: .
    env_file:
      - .env  # Load environment variables from .env file
    container_name: diarization
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    volumes:
      - ./input:/app/input  # Mount input directory
      - ./output:/app/output  # Mount output directory
      - ./:/app/
    working_dir: /app
